### ISSUE TITLE
breaking on python 2;

### ISSUE THREAD

**Issue by russ-te2** [pri22296/beautifultable#49]
This seems to be breaking on python 2.

```
>>> import beautifultable
>>> t = beautifultable.BeautifulTable()
>>> t.column_headers = ["a", "b", "c"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/russ/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beautifultable/beautifultable.py", line 231, in __setattr__
    super(BeautifulTable, self).__setattr__(name, value)
  File "/Users/russ/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beautifultable/beautifultable.py", line 366, in column_headers
    raise TypeError("Headers should be of type 'str', not {}".format(type(i)))
TypeError: Headers should be of type 'str', not <type 'str'>
```

**Comment by pri22296** [comment]
Are you using the latest version v0.6.0?

**Comment by russ-te2** [comment]
```
; /usr/local/bin/pip install beautifultable
Requirement already satisfied: beautifultable in /usr/local/lib/python2.7/site-packages (0.6.0)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/local/lib/python2.7/site-packages (from beautifultable) (1.1.6)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python2.7/site-packages (from beautifultable) (0.1.7)
; /usr/local/bin/python
Python 2.7.15 (default, Dec 27 2018, 11:55:59)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import beautifultable
>>> t = beautifultable.BeautifulTable()
>>> t.column_headers = ["a", "b", "c"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/beautifultable/beautifultable.py", line 231, in __setattr__
    super(BeautifulTable, self).__setattr__(name, value)
  File "/usr/local/lib/python2.7/site-packages/beautifultable/beautifultable.py", line 366, in column_headers
    raise TypeError("Headers should be of type 'str', not {}".format(type(i)))
TypeError: Headers should be of type 'str', not <type 'str'>
```

**Comment by pri22296** [comment]
In v0.6.0, there is a constraint that all strings must be unicode as mentioned [here](https://github.com/pri22296/beautifultable/blame/master/README.rst#L138). This wasn't in previous versions and will again be removed in v0.7.0

So in this case you can either replace 
```
t.column_headers = ["a", "b", "c"]
```
with 
```
t.column_headers = [u"a", u"b", u"c"]
```

or add
```
from __future__ import unicode_literals
```
at the top of the file as a temporary fix.

You could also downgrade to v0.5.3 if you do not need features added in v0.6.0

**Comment by taiwotman** [comment]
@pri22296 Using `from __future__ import unicode_literals` worked for me. Thanks for the workaround!
Fixes #49

**Comment by jayvdb** [comment]
```console
py27 run-test: commands[0] | python test.py

................EE....................................

======================================================================

ERROR: test_csv_export (__main__.TableOperationsTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "test.py", line 533, in test_csv_export

    self.table.to_csv('beautiful_table.csv')

  File "/home/travis/build/pri22296/beautifultable/beautifultable/beautifultable.py", line 1455, in to_csv

    with open(file_name, mode='wt', newline='') as csv_file:

TypeError: 'newline' is an invalid keyword argument for this function

======================================================================

ERROR: test_csv_import (__main__.TableOperationsTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "test.py", line 549, in test_csv_import

    self.table.to_csv('beautiful_table.csv')

  File "/home/travis/build/pri22296/beautifultable/beautifultable/beautifultable.py", line 1455, in to_csv

    with open(file_name, mode='wt', newline='') as csv_file:

TypeError: 'newline' is an invalid keyword argument for this function

----------------------------------------------------------------------

Ran 54 tests in 0.067s

FAILED (errors=2)
```
CI is failing on py2 atm https://travis-ci.org/pri22296/beautifultable/jobs/599527908

**Comment by pri22296** [comment]
@jayvdb Python2 support will be dropped in the next release. It's going EOL so there is no point in suporting it. I'll make some cleanup changes in travis, tox, etc in a future commit.
